ALTER TABLE item ADD COLUMN user_id BIGINT(20) NOT NULL AFTER id;
ALTER TABLE item_param ADD COLUMN user_id BIGINT(20) NOT NULL AFTER id;
ALTER TABLE item_param_value ADD COLUMN user_id BIGINT(20) NOT NULL AFTER id;
ALTER TABLE item_record ADD COLUMN user_id BIGINT(20) NOT NULL AFTER id;